

all:
	${MAKE} -C esp-hosted/esp_hosted_ng/host/ \
	CROSS_COMPILE=arm-rockchip830-linux-uclibcgnueabihf- \
	KERNEL=/home/lhn/Git/rv1106/luckfox-pico/sysdrv/source/kernel \
	target=spi


clean:
	${MAKE} -C esp-hosted/esp_hosted_ng/host/ clean \
	CROSS_COMPILE=arm-rockchip830-linux-uclibcgnueabihf- \
	KERNEL=/home/lhn/Git/rv1106/luckfox-pico/sysdrv/source/kernel \
	target=spi