#!/bin/sh

#ln -s /userdata/etc/dropbear /etc/dropbear

check_key()
{

	if ! touch /userdata/etc/dropbear 2>/dev/null
	then
		mkdir -p /userdata/etc/dropbear
	fi

	if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
		echo create /etc/dropbear/dropbear_rsa_host_key
    	dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
	fi

	if [ ! -f /etc/dropbear/dropbear_dss_host_key ]; then
		echo create /etc/dropbear/dropbear_dss_host_key
    	dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
	fi

	if [ ! -f /etc/dropbear/dropbear_ecdsa_host_key ]; then
		echo create /etc/dropbear/dropbear_ecdsa_host_key
    	dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
	fi

	if [ ! -f /etc/dropbear/dropbear_ed25519_host_key ]; then
		echo create /etc/dropbear/dropbear_ed25519_host_key
    	dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key
	fi

}

case $1 in
	start)
		killall dropbear
		check_key || exit 1
		/sbin/dropbear -E
		;;
	stop)
		killall dropbear
		;;
	*)
		exit 1
		;;
esac
